[project]
name = "simulacion-tp6"
version = "0.1.0"
description = ""
authors = [
    { name = "Ezequiel Saidman", email = "ezequiel.saidman@chevron.com" }
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "openpyxl>=3.1.5",
    "pandas>=2.3.1",
]

[project.scripts]
simulacion-tp6 = "simulacion_tp6:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[[tool.uv.index]]
name = "pypi-remote-internal"
url = "https://{ARTIFACTORY_USER}:{ARTIFACTORY_TOKEN}@artifactory.chevron.com/artifactory/api/pypi/pypi-remote/simple"
default = false
